# Generated by Django 3.2.4 on 2021-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='None', max_length=300, verbose_name='name for user'),
        ),
    ]
