# Generated by Django 3.2.4 on 2021-09-10 14:16

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('accounts', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.FloatField(default='0.0', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to=education.models.path_save_book, verbose_name='book pdf file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=education.models.path_save_book, verbose_name='awatar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=education.models.path_save_course, verbose_name='awatar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='translate',
            field=models.FileField(blank=True, null=True, upload_to=education.models.path_save_course, verbose_name='file translate'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='file',
            field=models.FileField(upload_to=education.models.path_save_coursevideo, verbose_name='file video'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to=accounts.models.path_save_teacher, verbose_name='awatar'),
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=300, verbose_name='device name')),
                ('os', models.CharField(max_length=300, verbose_name='os name')),
                ('date_joiin', models.DateField(verbose_name='date join device')),
                ('ip_device', models.GenericIPAddressField(verbose_name='ip address device')),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='session key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user name')),
            ],
            options={
                'verbose_name': 'session user device',
                'verbose_name_plural': 'ssessions user devices',
                'ordering': ('-id',),
            },
        ),
    ]
