# Generated by Django 3.2.4 on 2021-09-10 14:16

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblog',
            name='image',
            field=models.ImageField(upload_to=education.models.path_save_newsblog, verbose_name='awatar'),
        ),
    ]
